site_name: TRAQ Reporter
site_description: TRAQ Reporter uses the data captured with the TRAQ observer to make a client-ready view of each project. The reporter organizes the trees by project, maps the locations and organizes them by risk.
site_url: https://hammerdirt-analyst.github.io/traq-reporter/

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
  palette:
    - scheme: default
      primary: custom
      accent: custom
  logo: assets/branding/ourlogo.png
  favicon: assets/branding/ourlogo.png

nav:
  - Home: index.md
  - About: about.md
  - Briarwood: projects/briarwood.md
  - Arboretum: projects/arboretum.md
  - American River: projects/american-river.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - tables

extra_css:
  - assets/styles/extra.css

plugins:
  - search
